AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false